# Generated by Django 4.2.2 on 2023-06-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя и Фамилия')),
                ('presence', models.CharField(choices=[('yes', 'Я приду/мы придем'), ('no', 'Прийти не получится :('), ('later', 'Скажу ответ чуть позже')], default='later', max_length=5, verbose_name='Присутствие')),
                ('drink_preferences', models.CharField(blank=True, choices=[('shamp', 'Шампанское'), ('white_wine', 'Белое вино'), ('red_wine', 'Красное вино'), ('samogon', 'Папин самогон'), ('vodka', 'Водка'), ('kon', 'Коньяк'), ('no', 'А я и не пью')], max_length=20, null=True, verbose_name='Предпочтения по напиткам')),
                ('food_wishes', models.TextField(blank=True, null=True, verbose_name='Предпочтения по еде')),
            ],
        ),
    ]
