# Generated by Django 4.2.2 on 2023-06-23 07:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_guest_drink_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='drink_preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('shamp', 'Шампанское'), ('white_wine', 'Белое вино'), ('red_wine', 'Красное вино'), ('samogon', 'Папин самогон'), ('vodka', 'Водка'), ('kon', 'Коньяк'), ('no', 'А я и не пью')], max_length=200, null=True, verbose_name='Предпочтения по напиткам'),
        ),
    ]
